---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
  ansible_core:
    # Require minimum of 2.15 to get ansible-inventory --limit option
    package_pip: ansible-core>=2.16.4
  ansible_runner:
    package_pip: ansible-runner
  python: requirements.txt
    # git+https://github.com/ansible/ansible-sign
    # ncclient
    # paramiko
    # pykerberos
    # pyOpenSSL
    # pypsrp[kerberos,credssp]
    # pywinrm[kerberos,credssp]
    # toml
    # pexpect>=4.5
    # python-daemon
    # pyyaml
    # six
    # receptorctl
  system: |
    git-core [platform:rpm]
    python3.9-devel [platform:rpm compile]
    libcurl-devel [platform:rpm compile]
    krb5-devel [platform:rpm compile]
    krb5-workstation [platform:rpm]
    subversion [platform:rpm]
    subversion [platform:dpkg]
    git-lfs [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    epel-release [platform:rpm]
    python-unversioned-command [platform:rpm]
    unzip [platform:rpm]
    podman-remote [platform:rpm]
    cmake [platform:rpm compile]
    gcc [platform:rpm compile]
    gcc-c++ [platform:rpm compile]
    make [platform:rpm compile]
    openssl-devel [platform:rpm compile]

additional_build_steps:

  append_base:
    - RUN $PYCMD -m pip install -U pip